[features]
seeds = false
[programs.localnet]
stake_nft = "5nE3Ww1x63FDGzXuJT2cNmZsMn6xKymMVcShXBy3m2b"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/vipin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
